name: Test Kinemium Engine

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Rokit Init
        run: rokit init

      - name: Install Zune
        run: |
          rokit add Scythe-Technology/zune

      - name: Run headless tests
        run: zune run game --headless
