name: Test Kinemium Engine

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 3
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install Tools
        run: |
          rokit install --no-trust-check

      - name: Run headless tests
        run: zune run game --cli
